# Generated by Django 4.1.13 on 2024-12-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_charitypagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charitypagedata',
            name='payment_text_bg',
        ),
        migrations.RemoveField(
            model_name='charitypagedata',
            name='payment_text_en',
        ),
    ]
