# Generated by Django 4.1.13 on 2024-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_charitypagedata_payment_text_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitypagedata',
            name='charity_link_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
