# Generated by Django 4.1.13 on 2024-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_charitypagedata_charity_link_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charitypagedata',
            name='charity_link_name',
        ),
        migrations.AddField(
            model_name='charitypagedata',
            name='charity_link_name_bg',
            field=models.CharField(default='Благотворителност', max_length=255),
        ),
        migrations.AddField(
            model_name='charitypagedata',
            name='charity_link_name_en',
            field=models.CharField(default='Charity', max_length=255),
        ),
        migrations.AddField(
            model_name='charitypagedata',
            name='charity_tab_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charitypagedata',
            name='embedded_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charitypagedata',
            name='payment_info_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charitypagedata',
            name='payment_info_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charitypagedata',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
